routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

//Route::get('/dashboard', 'DashboardController@index');
//// Route::get('/system-management/{option}', 'SystemMgmtController@index');
//Route::get('/profile', 'ProfileController@index');

Route::group(['middleware' => ['web', 'auth']], function(){
    Route::get('/', function () {
        if(Auth::user()->level == 1){
            return view('dashboard');
        } else {
            return view('sourcingHome');
        }
    });

    Route::post('user-management/search', 'UserManagementController@search')->name('user-management.search');
    Route::resource('user-management', 'UserManagementController');

    Route::post('customer-management/search', 'CustomerManagementController@search')->name('customer-management.search');
    Route::resource('customer-management', 'CustomerManagementController');

    Route::post('vendor-management/search', 'VendorManagementController@search')->name('vendor-management.search');
    Route::resource('vendor-management', 'VendorManagementController');

    Route::post('fish-management/search', 'FishManagementController@search')->name('fish-management.search');
    Route::resource('fish-management', 'FishManagementController');

    Route::post('flocation-management/listData', 'FLocationManagementController@listData')->name('flocation-management.listData');
    Route::resource('flocation-management', 'FLocationManagementController');
});


//Route::group(['middleware' => ['web', 'checkuser:1']], function(){
//    Route::get('/', function () {
//        if(Auth::user()->level == 1){
//            return view('dashboard');
//        }
//    });
//
//    Route::post('user-management/search', 'UserManagementController@search')->name('user-management.search');
//    Route::resource('user-management', 'UserManagementController');
//});
//
//Route::group(['middleware' => ['web', 'checkuser:2']], function(){
//    Route::get('/', function () {
//        return view('sourcingHome');
//    })->middleware('auth');
//});

resources/views/fish-mgmt/base.blade.php
@extends('layouts.app-template')
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Fish Management
            </h1>
            <ol class="breadcrumb">
                <!-- li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li-->
                <li class="active">Fish Management</li>
            </ol>
        </section>
    @yield('action-content')
    <!-- /.content -->
    </div>
@endsection

resources/views/fish-mgmt/create.blade.php
@extends('fish-mgmt.base')

@section('action-content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Add new fish</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('fish-management.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('fish_name') ? ' has-error' : '' }}">
                                <label for="fish_name" class="col-md-4 control-label">Fish Name</label>

                                <div class="col-md-6">
                                    <input id="fish_name" type="text" class="form-control" name="fish_name" value="{{ old('fish_name') }}" required autofocus>

                                    @if ($errors->has('fish_name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('fish_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="avatar" class="col-md-4 control-label" >Picture</label>
                                <div class="col-md-6">
                                    <input type="file" id="picture" name="picture" required >
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
                                <label for="type" class="col-md-4 control-label">Type</label>

                                <div class="col-md-6">
                                    <input id="type" type="text" class="form-control" name="type" value="{{ old('type') }}" required>

                                    @if ($errors->has('type'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('type') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('size') ? ' has-error' : '' }}">
                                <label for="size" class="col-md-4 control-label">Size</label>

                                <div class="col-md-6">
                                    <input id="size" type="text" class="form-control" name="size" value="{{ old('size') }}" required>

                                    @if ($errors->has('size'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('size') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label for="description" class="col-md-4 control-label">Description</label>

                                <div class="col-md-6">
                                    <input id="description" type="text" class="form-control" name="description" value="{{ old('description') }}" required>

                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Create
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/fish-mgmt/edit.blade.php
@extends('fish-mgmt.base')

@section('action-content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Update Fish</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('fish-management.update', ['id' => $fish->id]) }}">
                            <input type="hidden" name="_method" value="PATCH">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">

                            <div class="form-group{{ $errors->has('fish_name') ? ' has-error' : '' }}">
                                <label for="fish_name" class="col-md-4 control-label">Fish Name</label>

                                <div class="col-md-6">
                                    <input id="fish_name" type="text" class="form-control" name="fish_name" value="{{ $fish->fish_name }}" required autofocus>

                                    @if ($errors->has('fish_name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('fish_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('pict') ? ' has-error' : '' }}">
                                <label for="pict" class="col-md-4 control-label">Picture</label>

                                <div class="col-md-6">
                                    <input id="pict" type="text" class="form-control" name="pict" value="{{ $fish->pict }}" required autofocus>

                                    @if ($errors->has('pict'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('pict') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('type') ? ' has-error' : '' }}">
                                <label for="type" class="col-md-4 control-label">Type</label>

                                <div class="col-md-6">
                                    <input id="type" type="text" class="form-control" name="type" value="{{ $fish->type }}" required>

                                    @if ($errors->has('type'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('type') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('size') ? ' has-error' : '' }}">
                                <label for="size" class="col-md-4 control-label">Size</label>

                                <div class="col-md-6">
                                    <input id="size" type="text" class="form-control" name="size" value="{{ $fish->size }}" required>

                                    @if ($errors->has('size'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('size') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label for="description" class="col-md-4 control-label">Description</label>

                                <div class="col-md-6">
                                    <input id="description" type="text" class="form-control" name="description" value="{{ $fish->description }}" required>

                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Update
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/fish-mgmt/index.blade.php
@extends('fish-mgmt.base')
@section('action-content')
    <!-- Main content -->
    <section class="content">
        <div class="box">
            <div class="box-header">
                <div class="row">
                    <div class="col-sm-8">
                        <h3 class="box-title">List of Fish</h3>
                    </div>
                    <div class="col-sm-4">
                        <a class="btn btn-primary" href="{{ route('fish-management.create') }}">Add new fish</a>
                    </div>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col-sm-6"></div>
                    <div class="col-sm-6"></div>
                </div>

                <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                <thead>
                                <tr role="row">
                                    <th width="10%" class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Name: activate to sort column descending" aria-sort="ascending">Fish Name</th>
                                    <th width="20%" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">Picture</th>
                                    <th width="20%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">Type</th>
                                    <th width="20%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">Size</th>
                                    <th width="20%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">Description</th>
                                    <th tabindex="0" aria-controls="example2" rowspan="1" colspan="2" aria-label="Action: activate to sort column ascending">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($fishes as $fish)
                                    <tr role="row" class="odd">
                                        <td class="sorting_1">{{ $fish->fish_name }}</td>
                                        <td>{{ $fish->pict }}</td>
                                        <td class="hidden-xs">{{ $fish->type }}</td>
                                        <td class="hidden-xs">{{ $fish->size }}</td>
                                        <td class="hidden-xs">{{ $fish->description }}</td>
                                        <td>
                                            <form class="row" method="POST" action="{{ route('fish-management.edit', ['id' => $fish->id]) }}" onsubmit = "return confirm('Are you sure?')">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <a href="{{ route('fish-management.edit', ['id' => $fish->id]) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                                                <a href="{{ route('fish-management.destroy', ['id' => $fish->id]) }}" class="btn btn-primary btn-sm"><i class="fa fa-trash"></i></a>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th width="10%" rowspan="1" colspan="1">Fish Name</th>
                                    <th width="20%" rowspan="1" colspan="1">Picture</th>
                                    <th class="hidden-xs" width="20%" rowspan="1" colspan="1">Type</th>
                                    <th class="hidden-xs" width="20%" rowspan="1" colspan="1">Size</th>
                                    <th class="hidden-xs" width="20%" rowspan="1" colspan="1">Description</th>
                                    <th rowspan="1" colspan="2">Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                            <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to {{count($fishes)}} of {{count($fishes)}} entries</div>
                        </div>
                        <div class="col-sm-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
    </section>
    <!-- /.content -->
    </div>
@endsection