routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();

//Route::get('/dashboard', 'DashboardController@index');
//// Route::get('/system-management/{option}', 'SystemMgmtController@index');
//Route::get('/profile', 'ProfileController@index');

Route::group(['middleware' => ['web', 'auth']], function(){
    Route::get('/', function () {
        if(Auth::user()->level == 1){
            return view('dashboard');
        } else {
            return view('sourcingHome');
        }
    });

    Route::post('user-management/search', 'UserManagementController@search')->name('user-management.search');
    Route::resource('user-management', 'UserManagementController');

    Route::post('customer-management/search', 'CustomerManagementController@search')->name('customer-management.search');
    Route::resource('customer-management', 'CustomerManagementController');

    Route::post('vendor-management/search', 'VendorManagementController@search')->name('vendor-management.search');
    Route::resource('vendor-management', 'VendorManagementController');

    Route::post('fish-management/search', 'FishManagementController@search')->name('fish-management.search');
    Route::resource('fish-management', 'FishManagementController');

    Route::post('flocation-management/listData', 'FLocationManagementController@listData')->name('flocation-management.listData');
    Route::resource('flocation-management', 'FLocationManagementController');
});


//Route::group(['middleware' => ['web', 'checkuser:1']], function(){
//    Route::get('/', function () {
//        if(Auth::user()->level == 1){
//            return view('dashboard');
//        }
//    });
//
//    Route::post('user-management/search', 'UserManagementController@search')->name('user-management.search');
//    Route::resource('user-management', 'UserManagementController');
//});
//
//Route::group(['middleware' => ['web', 'checkuser:2']], function(){
//    Route::get('/', function () {
//        return view('sourcingHome');
//    })->middleware('auth');
//});

resources/views/vendor-mgmt/base.blade.php
@extends('layouts.app-template')
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Vendor Management
            </h1>
            <ol class="breadcrumb">
                <!-- li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li-->
                <li class="active">Vendor Management</li>
            </ol>
        </section>
    @yield('action-content')
    <!-- /.content -->
    </div>
@endsection

resources/views/vendor-mgmt/create.blade.php
@extends('vendor-mgmt.base')

@section('action-content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Add new vendor</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('vendor-management.store') }}">
                            {{ csrf_field() }}

                            <div class="form-group{{ $errors->has('comp_title') ? ' has-error' : '' }}">
                                <label for="comp_title" class="col-md-4 control-label">Company Title</label>

                                <div class="col-md-6">
                                    <input id="comp_title" type="text" class="form-control" name="comp_title" value="{{ old('comp_title') }}" required autofocus>

                                    @if ($errors->has('comp_title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('comp_title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('comp_name') ? ' has-error' : '' }}">
                                <label for="comp_name" class="col-md-4 control-label">Customer Name</label>

                                <div class="col-md-6">
                                    <input id="comp_name" type="text" class="form-control" name="comp_name" value="{{ old('comp_name') }}" required autofocus>

                                    @if ($errors->has('comp_name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('comp_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                                <label for="address" class="col-md-4 control-label">Address</label>

                                <div class="col-md-6">
                                    <input id="address" type="address" class="form-control" name="address" value="{{ old('address') }}" required>

                                    @if ($errors->has('address'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('npwp') ? ' has-error' : '' }}">
                                <label for="npwp" class="col-md-4 control-label">NPWP</label>

                                <div class="col-md-6">
                                    <input id="npwp" type="text" class="form-control" name="npwp" value="{{ old('npwp') }}" required>

                                    @if ($errors->has('npwp'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('npwp') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('sap_num') ? ' has-error' : '' }}">
                                <label for="sap_num" class="col-md-4 control-label">Sap Number</label>

                                <div class="col-md-6">
                                    <input id="sap_num" type="text" class="form-control" name="sap_num" value="{{ old('sap_num') }}" required>

                                    @if ($errors->has('sap_num'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('sap_num') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Create
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vendor-mgmt/edit.blade.php
@extends('vendor-mgmt.base')

@section('action-content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Update vendor</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('vendor-management.update', ['id' => $vendor->id]) }}">
                            <input type="hidden" name="_method" value="PATCH">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <div class="form-group{{ $errors->has('comp_title') ? ' has-error' : '' }}">
                                <label for="comp_title" class="col-md-4 control-label">Company Title</label>

                                <div class="col-md-6">
                                    <input id="comp_title" type="text" class="form-control" name="comp_title" value="{{ $vendor->comp_title }}" required autofocus>

                                    @if ($errors->has('comp_title'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('comp_title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('comp_name') ? ' has-error' : '' }}">
                                <label for="comp_name" class="col-md-4 control-label">Customer Name</label>

                                <div class="col-md-6">
                                    <input id="comp_name" type="text" class="form-control" name="comp_name" value="{{ $vendor->comp_name }}" required autofocus>

                                    @if ($errors->has('comp_name'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('comp_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                                <label for="address" class="col-md-4 control-label">Address</label>

                                <div class="col-md-6">
                                    <input id="address" type="address" class="form-control" name="address" value="{{ $vendor->address }}" required>

                                    @if ($errors->has('address'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('npwp') ? ' has-error' : '' }}">
                                <label for="npwp" class="col-md-4 control-label">NPWP</label>

                                <div class="col-md-6">
                                    <input id="npwp" type="text" class="form-control" name="npwp" value="{{ $vendor->npwp }}" required>

                                    @if ($errors->has('npwp'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('npwp') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('sap_num') ? ' has-error' : '' }}">
                                <label for="sap_num" class="col-md-4 control-label">Sap Number</label>

                                <div class="col-md-6">
                                    <input id="sap_num" type="text" class="form-control" name="sap_num" value="{{$vendor->sap_num }}" required>

                                    @if ($errors->has('sap_num'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('sap_num') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Update
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vendor-mgmt/index.blade.php
@extends('vendor-mgmt.base')
@section('action-content')
    <!-- Main content -->
    <section class="content">
        <div class="box">
            <div class="box-header">
                <div class="row">
                    <div class="col-sm-8">
                        <h3 class="box-title">List of vendor</h3>
                    </div>
                    <div class="col-sm-4">
                        <a class="btn btn-primary" href="{{ route('vendor-management.create') }}">Add new vendor</a>
                    </div>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col-sm-6"></div>
                    <div class="col-sm-6"></div>
                </div>
                <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                <thead>
                                <tr role="row">
                                    <th width="10%" class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Name: activate to sort column descending" aria-sort="ascending">Company Title</th>
                                    <th width="20%" class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">Customer Name</th>
                                    <th width="20%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">Address</th>
                                    <th width="20%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">NPWP</th>
                                    <th width="20%" class="sorting hidden-xs" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Email: activate to sort column ascending">Sap Number</th>
                                    <th tabindex="0" aria-controls="example2" rowspan="1" colspan="2" aria-label="Action: activate to sort column ascending">Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($vendors as $vendor)
                                    <tr role="row" class="odd">
                                        <td class="sorting_1">{{ $vendor->comp_title }}</td>
                                        <td>{{ $vendor->comp_name }}</td>
                                        <td class="hidden-xs">{{ $vendor->address }}</td>
                                        <td class="hidden-xs">{{ $vendor->npwp }}</td>
                                        <td class="hidden-xs">{{ $vendor->sap_num }}</td>
                                        <td>
                                            <form class="row" method="POST" action="{{ route('vendor-management.destroy', ['id' => $vendor->id]) }}" onsubmit = "return confirm('Are you sure?')">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <a href="{{ route('vendor-management.edit', ['id' => $vendor->id]) }}" class="btn btn-warning col-sm-3 col-xs-5 btn-margin">
                                                    Update
                                                </a>
                                                {{--@if ($user->name != Auth::user()->name)--}}
                                                    <button type="submit" class="btn btn-danger col-sm-3 col-xs-5 btn-margin">
                                                        Delete
                                                    </button>
                                                {{--@endif--}}
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th width="10%" rowspan="1" colspan="1">Company Title</th>
                                    <th width="20%" rowspan="1" colspan="1">Customer Name</th>
                                    <th class="hidden-xs" width="20%" rowspan="1" colspan="1">Address</th>
                                    <th class="hidden-xs" width="20%" rowspan="1" colspan="1">NPWP</th>
                                    <th class="hidden-xs" width="20%" rowspan="1" colspan="1">Sap Number</th>
                                    <th rowspan="1" colspan="2">Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                            <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1 to {{count($vendor)}} of {{count($vendor)}} entries</div>
                        </div>
                        <div class="col-sm-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
    </section>
    <!-- /.content -->
    </div>
@endsection